language: python

os:
  - linux

python:
  - "3.6"
  - "3.7"
  - "3.8"

before_install:
  - "pip install -U pip"

# command to install dependencies
install:
  - python -m pip install cclib
  - python -m pip install codecov
  - python -m pip install periodictable
  - python -m pip install .
  - python -m pytest --version

# command to run tests
script:
  - python -m pytest -v test/ --cov=cantherm/

# After completion of tests
after_success:
  - codecov
