language: python

os:
  - linux
  - osx

python:
  - "3.4"
  - "3.5"

before_install:
  - "pip install -U pip"
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"

# command to install dependencies
install:
  - pip install -r travis-ci-requirements.txt

# command to run tests
script:
  - bash tests/runTests.sh # or py.test for Python versions 3.5 and below
